ALTER DATABASE `grufflie` CHARACTER SET utf8;
ALTER TABLE `items` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `item_metadata` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `users` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `tags` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `relations` CONVERT TO CHARACTER SET utf8;